triggers:
- description: null
  envs: []
  last_enabled_at: 2025-11-22 15:45:50.806986+00:00
  name: trigger daily jira
  pipeline_uuid: master_daily_jira
  schedule_interval: 0 8 * * *
  schedule_type: time
  settings: null
  sla: null
  start_time: 2026-01-01 12:00:00+00:00
  status: active
  token: c7399a2aabf544ea91155886e15d6997
  variables:
    pipeline_type: daily
