triggers:
- description: null
  envs: []
  last_enabled_at: 2025-12-16 19:26:34.892053+00:00
  name: trigger daily sharepoint
  pipeline_uuid: master_sharepoint
  schedule_interval: 0 7,11,15,19,22 * * *
  schedule_type: time
  settings: null
  sla: null
  start_time: 2025-12-16 08:00:00+00:00
  status: inactive
  token: 943d29e66b424d3aa896f6aea4c3878f
  variables:
    pipeline_type: daily
- description: null
  envs: []
  last_enabled_at: 2026-02-19 13:02:56.654472+00:00
  name: colossal labyrinth
  pipeline_uuid: master_sharepoint
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2026-02-18 13:02:00+00:00
  status: inactive
  token: c3a717bca8764bc2bd675ba01c574d85
  variables:
    pipeline_type: daily
